// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview An AI agent for generating chunk descriptions based on biome and nearby elements.
 *
 * - generateChunkDescription - A function that generates a chunk description.
 * - GenerateChunkDescriptionInput - The input type for the generateChunkDescription function.
 * - GenerateChunkDescriptionOutput - The return type for the generateChunkDescription function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateChunkDescriptionInputSchema = z.object({
  biome: z.string().describe('The biome of the chunk (e.g., forest, grassland, desert).'),
  nearbyElements: z.string().describe('A description of nearby elements in the chunk.'),
});
export type GenerateChunkDescriptionInput = z.infer<typeof GenerateChunkDescriptionInputSchema>;

const GenerateChunkDescriptionOutputSchema = z.object({
  description: z.string().describe('A generated description of the chunk.'),
});
export type GenerateChunkDescriptionOutput = z.infer<typeof GenerateChunkDescriptionOutputSchema>;

/**
 * Generates a description for a given chunk based on its biome and nearby elements.
 * @param input The input parameters including biome and nearby elements.
 * @returns A Promise that resolves to the generated chunk description.
 */
export async function generateChunkDescription(input: GenerateChunkDescriptionInput): Promise<GenerateChunkDescriptionOutput> {
  return generateChunkDescriptionFlow(input);
}

const generateChunkDescriptionPrompt = ai.definePrompt({
  name: 'generateChunkDescriptionPrompt',
  input: {
    schema: GenerateChunkDescriptionInputSchema,
  },
  output: {
    schema: GenerateChunkDescriptionOutputSchema,
  },
  prompt: `You are a game master generating descriptions for new chunks in the game world.

  Based on the biome and nearby elements, create an engaging and immersive description for the chunk.

  Biome: {{{biome}}}
  Nearby Elements: {{{nearbyElements}}}

  Description:`,
});

const generateChunkDescriptionFlow = ai.defineFlow(
  {
    name: 'generateChunkDescriptionFlow',
    inputSchema: GenerateChunkDescriptionInputSchema,
    outputSchema: GenerateChunkDescriptionOutputSchema,
  },
  async input => {
    const {output} = await generateChunkDescriptionPrompt(input);
    return output!;
  }
);
