// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview Defines the NPCBehavior flow, which uses AI to control non-player characters (NPCs) and their actions based on the game environment and player actions.
 *
 * @file npc-behavior.ts
 * @exports NPCBehaviorInput
 * @exports NPCBehaviorOutput
 * @exports npcBehavior
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const NPCBehaviorInputSchema = z.object({
  environmentDescription: z.string().describe('A description of the current game environment, including biomes and nearby entities.'),
  playerActions: z.string().describe('A description of the player\'s recent actions.'),
  npcName: z.string().describe('The name of the non-player character.'),
  npcDisposition: z.string().describe('The disposition of the non-player character, e.g. friendly, hostile, neutral.'),
});

export type NPCBehaviorInput = z.infer<typeof NPCBehaviorInputSchema>;

const NPCBehaviorOutputSchema = z.object({
  npcAction: z.string().describe('The action the NPC will take, based on the environment and player actions.'),
  npcDialogue: z.string().describe('The dialogue the NPC will speak, if any.'),
});

export type NPCBehaviorOutput = z.infer<typeof NPCBehaviorOutputSchema>;

/**
 * Executes the NPC behavior flow.
 * @param input The input parameters for the NPC behavior flow.
 * @returns A Promise that resolves to the NPC behavior output.
 */
export async function npcBehavior(input: NPCBehaviorInput): Promise<NPCBehaviorOutput> {
  return npcBehaviorFlow(input);
}

const npcBehaviorPrompt = ai.definePrompt({
  name: 'npcBehaviorPrompt',
  input: {
    schema: NPCBehaviorInputSchema,
  },
  output: {
    schema: NPCBehaviorOutputSchema,
  },
  prompt: `You are controlling a non-player character named {{npcName}} in a game. Your goal is to create believable and adaptive behavior for the NPC, influenced by the environment and the player\'s actions.

The NPC\'s disposition is: {{npcDisposition}}

The current environment is:
{{environmentDescription}}

The player has recently:
{{playerActions}}

Based on this information, decide on an action for the NPC and any dialogue they should speak. Consider the NPC\'s disposition and the environment when making your decision.

Action: {{npcAction}}
Dialogue: {{npcDialogue}}`,
});

const npcBehaviorFlow = ai.defineFlow(
  {
    name: 'npcBehaviorFlow',
    inputSchema: NPCBehaviorInputSchema,
    outputSchema: NPCBehaviorOutputSchema,
  },
  async input => {
    const {output} = await npcBehaviorPrompt(input);
    return output!;
  }
);

