/**
 * @file src/store/minimap.store.ts
 * @description Zustand store for minimap grid state
 *
 * @remarks
 * Manages minimap-specific state for independent grid updates:
 * - Grid data (chunks for display)
 * - Animation state (centering during move)
 * - Viewport size (5, 7, or 9)
 *
 * Grid updates are triggered by game state changes but stored here
 * so minimap re-renders independently from other HUD elements.
 */

import { create } from 'zustand';
import { devtools } from 'zustand/middleware';

export interface MinimapGridData {
  grid: any[][];
  centerX: number;
  centerY: number;
}

export interface MinimapAnimationState {
  isAnimatingMove: boolean;
  animationProgress: number; // 0-1
}

interface MinimapStoreState {
  // Grid data
  gridData: MinimapGridData;
  
  // Animation state
  animationState: MinimapAnimationState;
  
  // Viewport size
  viewportSize: 5 | 7 | 9;
  
  // Control methods
  setGridData: (grid: MinimapGridData) => void;
  setAnimationState: (state: Partial<MinimapAnimationState>) => void;
  setViewportSize: (size: 5 | 7 | 9) => void;
  
  // Bulk update from minimap logic
  updateGrid: (grid: any[][], centerX: number, centerY: number) => void;
  startAnimation: () => void;
  endAnimation: () => void;
}

/**
 * Minimap Store - Independent grid rendering
 *
 * @remarks
 * Used by MiniMapSection to subscribe to grid updates independently.
 * Grid updates don't trigger HUD or Dialog re-renders.
 *
 * Grid is generated by useMinimapGridData hook, then stored here.
 */
export const useMinimapStore = create<MinimapStoreState>()(
  devtools(
    (set) => ({
      gridData: {
        grid: [],
        centerX: 0,
        centerY: 0,
      },
      
      animationState: {
        isAnimatingMove: false,
        animationProgress: 0,
      },
      
      viewportSize: 5,
      
      setGridData: (grid) =>
        set(() => ({
          gridData: grid,
        })),
      
      setAnimationState: (state) =>
        set((prevState) => ({
          animationState: { ...prevState.animationState, ...state },
        })),
      
      setViewportSize: (size) =>
        set(() => ({
          viewportSize: size,
        })),
      
      updateGrid: (grid, centerX, centerY) =>
        set(() => ({
          gridData: {
            grid,
            centerX,
            centerY,
          },
        })),
      
      startAnimation: () =>
        set(() => ({
          animationState: {
            isAnimatingMove: true,
            animationProgress: 0,
          },
        })),
      
      endAnimation: () =>
        set(() => ({
          animationState: {
            isAnimatingMove: false,
            animationProgress: 0,
          },
        })),
    }),
    { name: 'MinimapStore' }
  )
);

// Atomic selectors
export const selectGridData = (state: MinimapStoreState) => state.gridData.grid;
export const selectGridCenter = (state: MinimapStoreState) => ({
  x: state.gridData.centerX,
  y: state.gridData.centerY,
});
export const selectAnimating = (state: MinimapStoreState) => state.animationState.isAnimatingMove;
export const selectViewportSize = (state: MinimapStoreState) => state.viewportSize;
