import {z} from 'zod';
import { ItemCategorySchema, PlayerAttributesSchema, SpawnConditionsSchema } from './base';
import type { EquipmentSlot, ItemCategory, PlayerAttributes, SpawnConditions, Terrain } from '../types';

// The effect an item can have when used.
export const ItemEffectSchema = z.object({
    type: z.enum(['HEAL', 'RESTORE_STAMINA', 'RESTORE_MANA']),
    amount: z.number(),
});
export type ItemEffect = z.infer<typeof ItemEffectSchema>;


// The relationship of an item to others, for crafting substitution.
export const ItemRelationshipSchema = z.object({
  substituteFor: z.string().optional().describe("The name of the 'base' item this item can substitute for (e.g., 'Da Thú Nhỏ' can substitute for 'Da Thú')."),
  quality: z.number().min(1).optional().describe("The quality of the substitution. Lower is better (e.g., 1 is a perfect substitute, 2 is a decent one)."),
});
export type ItemRelationship = z.infer<typeof ItemRelationshipSchema>;


// The full definition of an item, containing all its properties.
export const ItemDefinitionSchema = z.object({
  description: z.string(),
  tier: z.number(),
  category: ItemCategorySchema,
  subCategory: z.string().optional().describe("A more specific category like 'Meat', 'Fruit', 'Potion'."),
  emoji: z.string().describe("A single emoji that represents the item."),
  effects: z.array(ItemEffectSchema).describe("An array of effects the item provides when used."),
  baseQuantity: z.object({ min: z.number(), max: z.number() }),
  growthConditions: z.object({
    optimal: SpawnConditionsSchema,
    subOptimal: SpawnConditionsSchema,
  }).optional().describe("For living resources like plants or fungi, define the conditions under which they grow."),
  equipmentSlot: z.enum(['weapon', 'armor', 'accessory']).optional().describe("If the item is equippable, which slot it goes into."),
  attributes: PlayerAttributesSchema.optional().describe("The combat attributes this item provides when equipped."),
  relationship: ItemRelationshipSchema.optional().describe("How this item relates to others for crafting substitutions."),
});
export type ItemDefinition = z.infer<typeof ItemDefinitionSchema>;


// A version of the item definition specifically for items generated by AI.
// It includes spawn biome information.
export const GeneratedItemSchema = ItemDefinitionSchema.extend({
    spawnBiomes: z.array(z.string()).min(1).describe("An array of one or more biomes where this item can naturally be found."),
});
export type GeneratedItem = z.infer<typeof GeneratedItemSchema>;
